version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ../../../
      dockerfile: src/infra/docker/Dockerfile
    volumes:
      - ../../.././:/app/
    ports:
      - 3000:3000

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - ../../../.env
    environment:
      "MONGO_INITDB_ROOT_USERNAME": ${DATABASE_USER}
      "MONGO_INITDB_ROOT_PASSWORD": ${DATABASE_PASSWORD}